// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrxQYcGuJPZ8Hwpkanc6db_0bcnDYBsck',
    appId: '1:636719464865:web:2b2fd91189f1338d5f8be0',
    messagingSenderId: '636719464865',
    projectId: 'flutterfire-blog-9872d',
    authDomain: 'flutterfire-blog-9872d.firebaseapp.com',
    storageBucket: 'flutterfire-blog-9872d.firebasestorage.app',
    measurementId: 'G-E51DP2EL5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6EFU5K9LgVJJ2SuAKIMTZE1SUZem7mKM',
    appId: '1:636719464865:android:b203626d46e6e3e25f8be0',
    messagingSenderId: '636719464865',
    projectId: 'flutterfire-blog-9872d',
    storageBucket: 'flutterfire-blog-9872d.firebasestorage.app',
  );
}
